AllCops:
  NewCops: enable
#Gemspec/RequireMFA:
#  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Layout/LineLength:
  Max: 300
Lint/RescueException:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Max: 100
Metrics/BlockNesting:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Max: 300
Metrics/ParameterLists:
  Max: 10
Metrics/PerceivedComplexity:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false